package com.smt.domain;
// Generated 07-Nov-2016 17:32:39 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * AdminConfigDetails generated by hbm2java
 */
@Entity
@Table(name = "admin_config_details")
public class AdminConfigDetails implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String userId;
	private UserDetails userDetails;
	private String smtpHost;
	private String smtpPort;
	private String outlookPassword;
	private String outlookMail;

	public AdminConfigDetails() {
	}

	public AdminConfigDetails(UserDetails userDetails) {
		this.userDetails = userDetails;
	}

	public AdminConfigDetails(UserDetails userDetails, String smtpHost, String smtpPort, String outlookPassword,
			String outlookMail) {
		this.userDetails = userDetails;
		this.smtpHost = smtpHost;
		this.smtpPort = smtpPort;
		this.outlookPassword = outlookPassword;
		this.outlookMail = outlookMail;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "userDetails"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "userId", unique = true, nullable = false, length = 5)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public UserDetails getUserDetails() {
		return this.userDetails;
	}

	public void setUserDetails(UserDetails userDetails) {
		this.userDetails = userDetails;
	}

	@Column(name = "smtp_host", length = 45)
	public String getSmtpHost() {
		return this.smtpHost;
	}

	public void setSmtpHost(String smtpHost) {
		this.smtpHost = smtpHost;
	}

	@Column(name = "smtp_port", length = 45)
	public String getSmtpPort() {
		return this.smtpPort;
	}

	public void setSmtpPort(String smtpPort) {
		this.smtpPort = smtpPort;
	}

	@Column(name = "outlook_password", length = 45)
	public String getOutlookPassword() {
		return this.outlookPassword;
	}

	public void setOutlookPassword(String outlookPassword) {
		this.outlookPassword = outlookPassword;
	}

	@Column(name = "outlook_mail", length = 45)
	public String getOutlookMail() {
		return this.outlookMail;
	}

	public void setOutlookMail(String outlookMail) {
		this.outlookMail = outlookMail;
	}

}
