package com.smt.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * UserDetails generated by hbm2java
 */
@Entity
@Table(name = "user_details")
public class UserDetails implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String userId;
	private String userName;
	private String loginPassword;
	private String email;
	private String userRole;
	private AdminConfigDetails adminConfigDetails;

	public UserDetails() {
	}

	public UserDetails(String userId, String userName, String loginPassword) {
		this.userId = userId;
		this.userName = userName;
		this.loginPassword = loginPassword;
	}

	public UserDetails(String userId, String userName, String loginPassword, String email, String userRole,
			AdminConfigDetails adminConfigDetails) {
		this.userId = userId;
		this.userName = userName;
		this.loginPassword = loginPassword;
		this.email = email;
		this.userRole = userRole;
		this.adminConfigDetails = adminConfigDetails;
	}

	@Id
	@Column(name = "user_id", unique = true, nullable = false, length = 10)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "user_name", nullable = false, length = 45)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "login_password", nullable = false, length = 45)
	public String getLoginPassword() {
		return this.loginPassword;
	}

	public void setLoginPassword(String loginPassword) {
		this.loginPassword = loginPassword;
	}

	@Column(name = "email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "user_role", length = 45)
	public String getUserRole() {
		return this.userRole;
	}

	public void setUserRole(String userRole) {
		this.userRole = userRole;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "userDetails")
	public AdminConfigDetails getAdminConfigDetails() {
		return this.adminConfigDetails;
	}

	public void setAdminConfigDetails(AdminConfigDetails adminConfigDetails) {
		this.adminConfigDetails = adminConfigDetails;
	}

}
